// <auto-generated />
using System;
using ControleAtendimentos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ControleAtendimentos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260504030636_RestrictDeleteSetorPrioridade")]
    partial class RestrictDeleteSetorPrioridade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ControleAtendimentos.Models.AtendimentoModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("ChamadoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("dataHoraFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dataHoraInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("tempoTotal")
                        .HasColumnType("interval");

                    b.HasKey("id");

                    b.HasIndex("ChamadoId")
                        .IsUnique();

                    b.ToTable("Atendimentos");
                });

            modelBuilder.Entity("ControleAtendimentos.Models.ChamadoModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("prioridadeId")
                        .HasColumnType("integer")
                        .HasColumnName("prioridadeid");

                    b.Property<int>("setorId")
                        .HasColumnType("integer")
                        .HasColumnName("setorid");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("prioridadeId");

                    b.HasIndex("setorId");

                    b.ToTable("Chamados");
                });

            modelBuilder.Entity("ControleAtendimentos.Models.PrioridadeModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("tempoEstimado")
                        .HasColumnType("interval");

                    b.HasKey("id");

                    b.ToTable("Prioridades");
                });

            modelBuilder.Entity("ControleAtendimentos.Models.SetorModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Setores");
                });

            modelBuilder.Entity("ControleAtendimentos.Models.AtendimentoModel", b =>
                {
                    b.HasOne("ControleAtendimentos.Models.ChamadoModel", "chamado")
                        .WithOne("atendimento")
                        .HasForeignKey("ControleAtendimentos.Models.AtendimentoModel", "ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("chamado");
                });

            modelBuilder.Entity("ControleAtendimentos.Models.ChamadoModel", b =>
                {
                    b.HasOne("ControleAtendimentos.Models.PrioridadeModel", "prioridade")
                        .WithMany("chamados")
                        .HasForeignKey("prioridadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControleAtendimentos.Models.SetorModel", "setor")
                        .WithMany("chamados")
                        .HasForeignKey("setorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("prioridade");

                    b.Navigation("setor");
                });

            modelBuilder.Entity("ControleAtendimentos.Models.ChamadoModel", b =>
                {
                    b.Navigation("atendimento");
                });

            modelBuilder.Entity("ControleAtendimentos.Models.PrioridadeModel", b =>
                {
                    b.Navigation("chamados");
                });

            modelBuilder.Entity("ControleAtendimentos.Models.SetorModel", b =>
                {
                    b.Navigation("chamados");
                });
#pragma warning restore 612, 618
        }
    }
}
